services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - ./mongo_data:/data/db

networks:
  app-network:
    driver: bridge
